name: publish page
#Trigger for the workflow
  #Triggers only on push on master
on:
  pull-request:
    branches: [ "master" ]
      
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    strategy: 
      node-version: [12.x, 14.x, 16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set-up Node
        uses: actions/setup-node@v3
        with:
          node-version:  ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_REPO_TOKEN }}