name: publish page
#Trigger for the workflow
  #Triggers only on push on master
on:
  push:
    branches: [ "master" ]
      
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set-up Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install dependencies
        run: npm install

      - name: Install JSZip
        run: npm install jszip
        
      - name: Install github pages
        run: npm install gh-pages --save-dev
        
      - name: Install python dependencies
        run: pip install json-schema-for-humans
        
      - name: Run JSON Schema for humans
        run: sh src/doc2desc.sh

      - name: Build project
        run: npm run build
        
      - name: Deploy
        run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          git remote set-url origin https://${github_token}@github.com/${repository}
          npm run deploy
        env:
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
